# Generated by Django 3.2.18 on 2023-03-01 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='operation',
            name='express_cost',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='people',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='role',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='supplies',
            name='description',
            field=models.TextField(),
        ),
    ]
