# Generated by Django 3.2.18 on 2023-03-01 16:28

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siege_manager', '0002_auto_20230301_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='cover_image',
            field=cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image'),
        ),
    ]
