# Generated by Django 3.2.18 on 2023-03-06 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege_manager', '0003_role_cover_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='people_score',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='operation',
            name='supply_score',
            field=models.IntegerField(default=100),
        ),
    ]
