# Generated by Django 3.2.18 on 2023-03-08 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege_manager', '0008_auto_20230308_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='Attack_or_defend',
            field=models.CharField(default='defend', max_length=8),
        ),
    ]
