# Generated by Django 3.2.18 on 2023-03-16 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siege_manager', '0010_rename_attack_or_defend_operation_attack_or_defend'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='ability',
            field=models.TextField(default='to be added'),
        ),
    ]
